# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Kevin Marquette
# Generated on: 1/11/2018
@{
    RootModule        = 'PowerShell-Core-Compatibility-Alias.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '14905138-6639-4c1c-8297-e587f27dc943'
    Author            = 'Kevin Marquette'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Kevin Marquette. All rights reserved.'
    Description       = 'Adds aliases to PowerShell Core that were removed from Windows PowerShell'
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}
